services:
  qbittorrent-nox:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-nox
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=7777
    volumes:
      - ./config:/config
      - /disco_1tb/jellyfin-media:/jellyfin-media
    ports:
      - 7777:7777
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
networks: {}
