services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    dns:
      - 8.8.8.8 # Servidor DNS de Google
      - 1.1.1.1 # Servidor DNS de Cloudflare
networks: {}
x-dockge:
  urls: []
