services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    user: 1000:1000
    read_only: true
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    environment:
      - CLOUDFLARE_API_TOKEN=TOKEN
      - DOMAINS=example.cesarcorral.cc
      - PROXIED=false
networks: {}
